export const SET_USER_PENDING = "SET_USER_PENDING";
export const SET_USER_FETCHED = "SET_USER_FETCHED";
export const SET_USER_REJECTED = "SET_USER_REJECTED";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";

export const ADD_FORM_DATA_PENDING = "ADD_FORM_DATA_PENDING";
export const ADD_FORM_DATA_DEPLOYED = "ADD_FORM_DATA_DEPLOYED";
export const ADD_FORM_DATA_REJECTED = "ADD_FORM_DATA_REJECTED";
export const FETCH_ORGANIZATIONS_PENDING = "FETCH_ORGANIZATIONS_PENDING";
export const FETCH_ORGANIZATIONS_FETCHED = "FETCH_ORGANIZATIONS_FETCHED";
export const FETCH_ORGANIZATIONS_REJECTED = "FETCH_ORGANIZATIONS_REJECTED";
