export const SET_USER_PENDING = "SET_USER_PENDING";
export const SET_USER_FETCHED = "SET_USER_FETCHED";
export const SET_USER_REJECTED = "SET_USER_REJECTED";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";
export const USER_NOT_LOGGED = "USER_NOT_LOGGED";
export const USER_LOGGED = "USER_LOGGED";
